# Generated by Django 2.2.5 on 2021-02-09 17:34

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('seating_capacity', models.PositiveSmallIntegerField()),
                ('web_lecture_support', models.BooleanField(default=False)),
                ('shape', models.CharField(choices=[('oval', 'oval'), ('rectangular', 'rectangular'), ('canopy', 'canopy'), ('elevated', 'elevated')], default=('oval', 'oval'), max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('doj', models.DateField(auto_now_add=True)),
                ('standard', models.CharField(max_length=20)),
                ('roll_no', models.PositiveSmallIntegerField()),
                ('ranking', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('total_durations', models.IntegerField()),
                ('per_class_duration', models.IntegerField(validators=[django.core.validators.MinLengthValidator(30), django.core.validators.MaxValueValidator(120)])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('doj', models.DateField(auto_now_add=True)),
                ('subjects', django.contrib.postgres.fields.jsonb.JSONField()),
                ('salary', models.PositiveIntegerField()),
                ('takes_web_lecture', models.BooleanField(default=False)),
            ],
        ),
    ]
