# Generated by Django 2.2.5 on 2021-02-09 18:46

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='shape',
            field=models.CharField(choices=[('O', 'oval'), ('R', 'rectangular'), ('C', 'canopy'), ('E', 'elevated')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='chapters',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=jsonfield.fields.JSONField(),
        ),
    ]
