# Generated by Django 2.2.5 on 2021-02-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0003_subject_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='total_durations',
            new_name='total_duration',
        ),
    ]
