# Generated by Django 2.2.5 on 2021-02-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_auto_20210210_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectTeacherMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('subject_id', models.IntegerField()),
                ('teacher_id', models.IntegerField()),
            ],
        ),
    ]
