# Generated by Django 2.2.5 on 2021-02-10 16:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0005_studentsubjectteachermapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsPointOfContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatives_name', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('relationship', models.TextField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolApp.Student')),
            ],
        ),
    ]
