# Generated by Django 2.2.5 on 2021-02-10 17:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0006_studentspointofcontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspointofcontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
