# Generated by Django 2.2.5 on 2021-02-13 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0008_auto_20210213_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentspointofcontact',
            old_name='student_id',
            new_name='student',
        ),
    ]
