# Generated by Django 2.2.5 on 2021-02-13 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0009_auto_20210213_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentspointofcontact',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='SchoolApp.Student'),
        ),
    ]
