# Generated by Django 2.2.5 on 2021-02-13 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0011_auto_20210213_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='per_class_duration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinLengthValidator(30), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='total_duration',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
