# Generated by Django 2.2.5 on 2021-02-13 10:36

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0013_auto_20210213_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='chapters',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
