# Generated by Django 2.2.5 on 2021-02-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0015_auto_20210213_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='shape',
            field=models.CharField(choices=[('O', 'Oval'), ('R', 'Rectangular'), ('C', 'Canopy'), ('E', 'Elevated')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='studentspointofcontact',
            name='relationship',
            field=models.CharField(choices=[('F', 'Father'), ('M', 'Mother'), ('S', 'Sister'), ('B', 'Brother'), ('U', 'Uncle'), ('A', 'Aunt')], default='F', max_length=1),
        ),
    ]
