# Generated by Django 2.2.5 on 2021-02-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0017_auto_20210213_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='doj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='doj',
            field=models.DateField(),
        ),
    ]
